export const STORES = [
    'Amazon Fresh',
    'Costco',
    'Dollarama',
    'Farm Boy',
    'Food Basics',
    'Foodland',
    'Fortinos',
    'FreshCo',
    'H Mart',
    'IGA',
    'Instacart',
    'Loblaws',
    "Longo's",
    'Maxi',
    'Metro',
    'No Frills',
    'Provigo',
    'Real Atlantic Superstore',
    'Real Canadian Superstore',
    'Safeway',
    'Save-On-Foods',
    'Shoppers Drug Mart',
    'Sobeys',
    'Super C',
    'T&T Supermarket',
    'Target',
    'Uber Eats',
    'Walmart',
    'Your Independent Grocer',
    'Zehrs',
];
