export const Stores = [
    { label: 'Amazon Fresh', value: 'Amazon Fresh' },
    { label: 'Costco', value: 'Costco' },
    { label: 'Dollarama', value: 'Dollarama' },
    { label: 'Farm Boy', value: 'Farm Boy' },
    { label: 'Food Basics', value: 'Food Basics' },
    { label: 'Foodland', value: 'Foodland' },
    { label: 'Fortinos', value: 'Fortinos' },
    { label: 'FreshCo', value: 'FreshCo' },
    { label: 'H Mart', value: 'H Mart' },
    { label: 'IGA', value: 'IGA' },
    { label: 'Instacart', value: 'Instacart' },
    { label: 'Loblaws', value: 'Loblaws' },
    { label: "Longo's", value: "Longo's" },
    { label: 'Maxi', value: 'Maxi' },
    { label: 'Metro', value: 'Metro' },
    { label: 'No Frills', value: 'No Frills' },
    { label: 'Provigo', value: 'Provigo' },
    { label: 'Real Atlantic Superstore', value: 'Real Atlantic Superstore' },
    { label: 'Real Canadian Superstore', value: 'Real Canadian Superstore' },
    { label: 'Safeway', value: 'Safeway' },
    { label: 'Save-On-Foods', value: 'Save-On-Foods' },
    { label: 'Shoppers Drug Mart', value: 'Shoppers Drug Mart' },
    { label: 'Sobeys', value: 'Sobeys' },
    { label: 'Super C', value: 'Super C' },
    { label: 'T&T Supermarket', value: 'T&T Supermarket' },
    { label: 'Target', value: 'Target' },
    { label: "Trader Joe's", value: "Trader Joe's" },
    { label: 'Uber Eats', value: 'Uber Eats' },
    { label: 'Walmart', value: 'Walmart' },
    { label: 'Your Independent Grocer', value: 'Your Independent Grocer' },
    { label: 'Zehrs', value: 'Zehrs' },
];
