export const Categories = [
    'Baked Goods',
    'Beverages',
    'Canned Goods',
    'Condiments',
    'Dairy',
    'Dry Goods',
    'Eggs',
    'Frozen Foods',
    'Fruits',
    'Grains',
    'Meat',
    'Nuts',
    'Oils',
    'Sauces',
    'Seafood',
    'Snacks',
    'Spices',
    'Vegetables',
];
